const text = [
  `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt blanditiis consequatur eveniet repudiandae ducimus consectetur ipsa praesentium fugiat nulla iusto. Recusandae expedita eveniet officia necessitatibus eum alias nesciunt fuga saepe dolorum nostrum incidunt enim esse, excepturi vitae sed aut quae consequuntur culpa similique atque consectetur sequi quam? Quia, dolore similique magnam et quaerat fuga quisquam placeat id sint ad reiciendis veniam doloremque exercitationem sed non in magni minus repudiandae. Quae temporibus illo soluta dolorem nostrum cupiditate praesentium, doloribus est necessitatibus dignissimos culpa obcaecati tempore ullam magni! Optio ipsam iste veniam officiis dolores necessitatibus, enim incidunt expedita quae deleniti, quibusdam cumque?`, 
  `Quae temporibus illo soluta dolorem nostrum cupiditate praesentium, doloribus est necessitatibus dignissimos culpa obcaecati tempore ullam magni!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt blanditiis consequatur eveniet repudiandae ducimus consectetur ipsa praesentium fugiat nulla iusto. Recusandae expedita eveniet officia necessitatibus eum alias nesciunt fuga saepe dolorum nostrum incidunt enim esse, excepturi vitae sed aut quae consequuntur culpa similique atque consectetur sequi quam? Quia, dolore similique magnam et quaerat fuga quisquam placeat id sint ad reiciendis veniam doloremque exercitationem sed non in magni minus repudiandae.  Optio ipsam iste veniam officiis dolores necessitatibus, enim incidunt expedita quae deleniti, quibusdam cumque?`,
    `Nesciunt blanditiis consequatur eveniet repudiandae ducimus consectetur ipsa praesentium fugiat nulla iusto. Quae temporibus illo soluta dolorem nostrum cupiditate praesentium, doloribus est necessitatibus dignissimos culpa obcaecati tempore ullam magni!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Recusandae expedita eveniet officia necessitatibus eum alias nesciunt fuga saepe dolorum nostrum incidunt enim esse, excepturi vitae sed aut quae consequuntur culpa similique atque consectetur sequi quam? Quia, dolore similique magnam et quaerat fuga quisquam placeat id sint ad reiciendis veniam doloremque exercitationem sed non in magni minus repudiandae.  Optio ipsam iste veniam officiis dolores necessitatibus, enim incidunt expedita quae deleniti, quibusdam cumque?`,
  `Recusandae expedita eveniet officia necessitatibus eum alias nesciunt fuga saepe dolorum nostrum incidunt enim esse, excepturi vitae sed aut quae consequuntur culpa similique atque consectetur sequi quam?Nesciunt blanditiis consequatur eveniet repudiandae ducimus consectetur ipsa praesentium fugiat nulla iusto. Quae temporibus illo soluta dolorem nostrum cupiditate praesentium, doloribus est necessitatibus dignissimos culpa obcaecati tempore ullam magni!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quia, dolore similique magnam et quaerat fuga quisquam placeat id sint ad reiciendis veniam doloremque exercitationem sed non in magni minus repudiandae.  Optio ipsam iste veniam officiis dolores necessitatibus, enim incidunt expedita quae deleniti, quibusdam cumque?`,
  `Quia, dolore similique magnam et quaerat fuga quisquam placeat id sint ad reiciendis veniam doloremque exercitationem sed non in magni minus repudiandae.  Recusandae expedita eveniet officia necessitatibus eum alias nesciunt fuga saepe dolorum nostrum incidunt enim esse, excepturi vitae sed aut quae consequuntur culpa similique atque consectetur sequi quam?Nesciunt blanditiis consequatur eveniet repudiandae ducimus consectetur ipsa praesentium fugiat nulla iusto. Quae temporibus illo soluta dolorem nostrum cupiditate praesentium, doloribus est necessitatibus dignissimos culpa obcaecati tempore ullam magni!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Optio ipsam iste veniam officiis dolores necessitatibus, enim incidunt expedita quae deleniti, quibusdam cumque?`, 
  `Quae temporibus illo soluta dolorem nostrum cupiditate praesentium, doloribus est necessitatibus dignissimos culpa obcaecati tempore ullam magni!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt blanditiis consequatur eveniet repudiandae ducimus consectetur ipsa praesentium fugiat nulla iusto. Recusandae expedita eveniet officia necessitatibus eum alias nesciunt fuga saepe dolorum nostrum incidunt enim esse, excepturi vitae sed aut quae consequuntur culpa similique atque consectetur sequi quam? Quia, dolore similique magnam et quaerat fuga quisquam placeat id sint ad reiciendis veniam doloremque exercitationem sed non in magni minus repudiandae.  Optio ipsam iste veniam officiis dolores necessitatibus, enim incidunt expedita quae deleniti, quibusdam cumque?`,
    `Nesciunt blanditiis consequatur eveniet repudiandae ducimus consectetur ipsa praesentium fugiat nulla iusto. Quae temporibus illo soluta dolorem nostrum cupiditate praesentium, doloribus est necessitatibus dignissimos culpa obcaecati tempore ullam magni!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Recusandae expedita eveniet officia necessitatibus eum alias nesciunt fuga saepe dolorum nostrum incidunt enim esse, excepturi vitae sed aut quae consequuntur culpa similique atque consectetur sequi quam? Quia, dolore similique magnam et quaerat fuga quisquam placeat id sint ad reiciendis veniam doloremque exercitationem sed non in magni minus repudiandae.  Optio ipsam iste veniam officiis dolores necessitatibus, enim incidunt expedita quae deleniti, quibusdam cumque?`,
  `Recusandae expedita eveniet officia necessitatibus eum alias nesciunt fuga saepe dolorum nostrum incidunt enim esse, excepturi vitae sed aut quae consequuntur culpa similique atque consectetur sequi quam?Nesciunt blanditiis consequatur eveniet repudiandae ducimus consectetur ipsa praesentium fugiat nulla iusto. Quae temporibus illo soluta dolorem nostrum cupiditate praesentium, doloribus est necessitatibus dignissimos culpa obcaecati tempore ullam magni!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quia, dolore similique magnam et quaerat fuga quisquam placeat id sint ad reiciendis veniam doloremque exercitationem sed non in magni minus repudiandae.  Optio ipsam iste veniam officiis dolores necessitatibus, enim incidunt expedita quae deleniti, quibusdam cumque?`,
  `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt blanditiis consequatur eveniet repudiandae ducimus consectetur ipsa praesentium fugiat nulla iusto. Recusandae expedita eveniet officia necessitatibus eum alias nesciunt fuga saepe dolorum nostrum incidunt enim esse, excepturi vitae sed aut quae consequuntur culpa similique atque consectetur sequi quam? Quia, dolore similique magnam et quaerat fuga quisquam placeat id sint ad reiciendis veniam doloremque exercitationem sed non in magni minus repudiandae. Quae temporibus illo soluta dolorem nostrum cupiditate praesentium, doloribus est necessitatibus dignissimos culpa obcaecati tempore ullam magni! Optio ipsam iste veniam officiis dolores necessitatibus, enim incidunt expedita quae deleniti, quibusdam cumque?`, 
];
  
const form = document.querySelector('.lorem-form');
const amount = document.getElementById('amount');
const result = document.querySelector('.lorem-text');

form.addEventListener('submit', function(e){
  e.preventDefault();
  const value = parseInt(amount.value);
  const random = Math.floor(Math.random() * text.length);
  //empty value
  //-1  >9
  
  if(isNaN(value) || value <= 0 || value > 9){
    result.innerHTML = `<p class="result">${text[random]}</p>`;
    alert("Sorry, Dude! Choose number from 0 - 9");
  }
  else {
    let tempText = text.slice(0, value);
    tempText = tempText.map(function(item){
      return `<p class="result">${item}</p>`;
    })
    .join("");
    result.innerHTML = tempText;
  }
  
})
